# Generated by Django 6.0.2 on 2026-02-04 20:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text="e.g. 'Build a React Todo App'", max_length=255)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('token_usage', models.IntegerField(blank=True, null=True)),
                ('file_count', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Step',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent'), ('system', 'System')], max_length=20)),
                ('step_type', models.CharField(choices=[('prompt', 'Prompt'), ('tool_call', 'Tool Call'), ('diff', 'Code Diff'), ('thought', 'Thinking'), ('text', 'Text Response')], max_length=20)),
                ('content', models.TextField(help_text='The raw content of the step')),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('order', models.IntegerField(default=0, help_text='Sequence number in the session')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='core.session')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SteeringTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('pivot', 'Pivot'), ('correction', 'Correction'), ('architecture', 'Architectural Decision')], max_length=50)),
                ('comment', models.TextField(blank=True, help_text='Why was this important?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='core.step')),
            ],
        ),
    ]
