# Generated by Django 6.0.2 on 2026-02-04 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='hero_moment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hero_sessions', to='core.step'),
        ),
        migrations.AddField(
            model_name='session',
            name='summary',
            field=models.TextField(blank=True, help_text='AI-generated or user-written summary'),
        ),
        migrations.AddField(
            model_name='steeringtag',
            name='after_snapshot',
            field=models.TextField(blank=True, help_text='Code context after the change'),
        ),
        migrations.AddField(
            model_name='steeringtag',
            name='before_snapshot',
            field=models.TextField(blank=True, help_text='Code context before the change'),
        ),
        migrations.AddField(
            model_name='steeringtag',
            name='impact_score',
            field=models.IntegerField(default=5, help_text='1-10 scale of importance'),
        ),
    ]
