# Generated by Django 6.0.2 on 2026-02-07 11:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_session_hero_moment_session_summary_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='source',
            field=models.CharField(choices=[('claudecode', 'Claude Code'), ('cursor', 'Cursor'), ('windsurf', 'Windsurf'), ('copilot', 'GitHub Copilot'), ('upload', 'Manual Upload')], default='upload', max_length=20),
        ),
        migrations.AddField(
            model_name='session',
            name='source_session_id',
            field=models.CharField(blank=True, default='', help_text='Original session ID from the source tool', max_length=255),
        ),
        migrations.AddField(
            model_name='session',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL),
        ),
    ]
