# Generated by Django 6.0.2 on 2026-02-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_session_source_session_source_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='session',
            name='content_hash',
            field=models.CharField(blank=True, db_index=True, default='', help_text='SHA-256 hash of uploaded content for dedup', max_length=64),
        ),
    ]
